config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    # get 'sign_in',    to: 'devise/sessions#new', :as => :new_user_session
    # get 'sign_out',   to: 'devise/sessions#destroy', as: :destroy_user_session
    # get 'join',     to: 'devise/registrations#new'
    # get 'settings', to: 'devise/registrations#edit'
    # get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'about', to: 'noto#about'
  get 'ui',    to: 'noto#ui'

  scope '/notes' do
    get '/', to: 'noto#index', as: 'notes'
    get '/new', to: 'note#new', as: 'new_note'
    get '/:id', to: 'notes#show', as: 'note'
  end

  root 'noto#index'
end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Canable::Ables

  field :title,     type: String, default: 'Untitled'
  field :text,      type: String, default: ''
  field :html,      type: String
  field :permalink, type: String

  before_validation :html!, :permalink!

  validates :title, presence: true

  belongs_to :user

  def viewable_by?(u)
    u == self.user || u.admin?
  end

  def creatable_by?(u)
    true
  end

  def updatable_by?(u)
    u == self.user || u.admin?
  end

  def destroyable_by?(u)
    u == self.user || u.admin?
  end

  protected

  def html!
    markdown = Rails.configuration.markdown

    self.html = markdown.render(self.text)
  end

  def permalink!
    unless self.permalink
      str = self.title

      str = str.gsub(/[^0-9a-z ]/i, '')
      str = str.gsub(/ /, '-')
      str = str.downcase

      count = Note.where(
        user_id: self.user_id,
        permalink: /#{Regexp.quote(str)}/
      ).count

      if count > 1
        str ="#{str}-#{count + 1}"
      end

      self.permalink = str
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Canable::Ables
  include Canable::Cans

  field :email,    type: String
  field :name,     type: String
  field :admin,    type: Boolean, default: false

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:dropbox_oauth2]

  field :provider, type: String
  field :uid, type: String

  field :encrypted_password, type: String

  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  field :remember_created_at, type: Time

  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  validates :email,    presence: true, uniqueness: true

  has_many :notes

  def viewable_by?(u)
    u == self || u.admin?
  end

  def creatable_by?(u)
    true
  end

  def updatable_by?(u)
    u == self || u.admin?
  end

  def destroyable_by?(u)
    u == self || u.admin?
  end

  def self.from_omniauth(auth)
    d { auth }
    d { auth.token }
    d { auth.extra.raw_info.email }

    u = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.extra.raw_info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.extra.raw_info.display_name
    end

    d { u }

    u
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.dropbox_oauth2'] && session['devise.dropbox_oauth2']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  # Workaround for serialization issues with Moped (see
  #   https://github.com/plataformatec/devise/pull/2882).
  class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]['$oid'])
      record if record && record.authenticatable_salt == salt
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
  end

  def new
  end
end

app/controllers/noto_controller.rb
class NotoController < ApplicationController
  layout 'page'

  def index
    if current_user
      render 'notes/index', layout: 'application'
    else

    end
  end

  def about
  end

  def ui
    render 'noto/ui', layout: 'application'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def dropbox_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Dropbox') if is_navigational_format?
    else
      session['devise.dropbox_oauth2_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!5
%html{lang: 'en'}
  %head
    %title Noto

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = csrf_meta_tags

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    %script{src: "//use.typekit.net/idh3uav.js"}
    :coffeescript
      try
        Typekit.load()
      catch error
        console.log error

  %body
    %header#header
      %aside
        %h1= link_to 'Noto', root_path
      %nav
        %ul
          %li= link_to 'Logout', destroy_user_session_path, method: :delete
    %main{role: 'main'}
      = yield

app/views/layouts/page.html.haml
!!!5
%html{lang: 'en'}
  %head
    %title Noto

    = stylesheet_link_tag 'page', media: 'all', 'data-turbolinks-track' => true

    = csrf_meta_tags

    = javascript_include_tag 'page', 'data-turbolinks-track' => true

    %script{src: "//use.typekit.net/idh3uav.js"}
    :coffeescript
      try
        Typekit.load()
      catch error
        console.log error

  %body
    %header#header
      %nav
        %ul
          %li= link_to "Login with Dropbox"
          -# %li= link_to "Join", join_path
          -# %li= link_to "Login", login_path
      %h1= link_to "Noto", root_path

    %main{role: 'main'}
      = yield

    %footer#footer
      %aside
        %p= "&copy; #{Time.now.year} <a href='#'>Noto</a>.".html_safe
      %nav
        %ul
          %li= link_to "About", about_path
          %li= link_to "Support"

app/views/notes/index.html.haml
.notes
  %header
    %nav
      = link_to 'New', new_note_path, class: 'btn btn-blue'
  %article.note
    %section
      %p= link_to 'This is a title'
    %aside
      %p Nov 23, 2014, 10:33 AM
  %article.note
    %section
      %p= link_to 'This is a title'
    %aside
      %p Nov 23, 2014, 10:33 AM
  %article.note
    %section
      %p= link_to 'This is a title'
    %aside
      %p Nov 23, 2014, 10:33 AM
  %article.note
    %section
      %p= link_to 'This is a title'
    %aside
      %p Nov 23, 2014, 10:33 AM

app/views/noto/about.html.haml
.page
  %header
    %h2 About
  %p All about Noto.

app/views/noto/index.html.haml
.hero
  %h2 Notes, simplified.
  %p Noto is a simple way to take notes and keep them with you, wherever you are.
  %nav
    %ul
      %li= link_to "Login with Dropbox", user_omniauth_authorize_path(:dropbox_oauth2), class: "btn btn-blue"
      -# %li= link_to "Login", login_path, class: "btn"

app/views/noto/ui.html.haml
%header#header
  Stuff

app/views/partials/_flash.html.haml
- if flash[:notice]
  .flash.notice
    %p= flash[:notice]

- if flash[:error]
  .flash.error
    %p= flash[:error]

- if defined?(resource) && !resource.errors.blank?
  - messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join

  .flash.error
    = messages.html_safe